# 欢迎使用 Jekyll!
#
# 这个配置文件用于影响全站的设置，通常只需要设置一次，
# 之后很少改动。
# 出于技术原因，使用 `jekyll serve` 时该文件不会自动重载。
# 如果修改了它，请重启服务进程。

# 站点设置
title                    : "Jie Qi" # 浏览器/SEO 标题（不是导航栏标签）
#description              : "I am a professor" # 侧栏作者卡片简介 + SEO 描述
repository               : "HaoYuanTian/HaoYuanTian.github.io" # GitHub "owner/repo"，用于链接和元数据
# google_scholar_stats_use_cdn : true # 通过 CDN 加载 Scholar 统计资源

# Google Analytics
google_analytics_id      :  # 从 https://analytics.google.com/analytics/ 获取

# SEO 相关
google_site_verification :  # 从 https://search.google.com/search-console/about 获取
bing_site_verification   :  # 从 https://www.bing.com/webmasters/about 获取
baidu_site_verification  :  # 从 https://ziyuan.baidu.com/login/index?u=/site/index 获取

# 作者信息
author:
  name             : "Jie Qi" # 侧栏作者姓名
  avatar           : "images/android-chrome-512x512.png" # 侧栏头像
  bio              :  # 侧栏作者简介
  location         : "Address: Building 2, Room 2221,<br>No 2999 North Renmin Road, Songjiang,<br>Shanghai, China" # 侧栏位置
  employer         : "Department of Automation,<br>School of Information and Intelligent Science,<br>Donghua University" # 侧栏单位/机构
  pubmed           : # 侧栏社交链接
  googlescholar    : "https://scholar.google.com/citations?user=gvp5ojgAAAAJ&hl=zh-CN&oi=ao" # 侧栏社交链接
  email            : "jieqi@dhu.edu.cn" # 侧栏邮箱链接
  researchgate     :  # 例如 "https://www.researchgate.net/profile/yourprofile"
  uri              : # 侧栏个人网站链接
  bitbucket        :
  codepen          :
  dribbble         :
  flickr           :
  facebook         :
  foursquare       :
  github           : # 侧栏社交链接
  google_plus      :
  keybase          :
  instagram        :
  impactstory      : # 例如 "https://profiles.impactstory.org/u/xxxx-xxxx-xxxx-xxxx"
  lastfm           :
  linkedin         : # 侧栏社交链接
  dblp             : # 侧栏社交链接
  orcid            : # 侧栏社交链接
  pinterest        :
  soundcloud       :
  stackoverflow    : # 侧栏社交链接
  steam            :
  tumblr           :
  twitter          : 
  vine             :
  weibo            :
  xing             :
  youtube          :
  wikipedia        :


# 读取文件
include:
  - .htaccess
  - _pages
  - files
exclude:
  - docs
  - google_scholar_crawler
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - .github
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8" # 确保输出编码一致
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# 转换
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown 处理
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false # 使用 Rouge 代替 CodeRay

# 默认值
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      author_profile: true


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # 压缩编译后的 CSS


# 输出
permalink: /:categories/:title/
timezone: Asia/Shanghai # 影响日期显示


# 插件
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
# 使用 --safe 时模拟 GitHub Pages
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# HTML 压缩
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
